backend:
  name: git-gateway
  branch: main  # Change to 'master' if your repo default branch is master

media_folder: "images/projects"
public_folder: "/images/projects"

collections:
  - name: "photos"
    label: "Gallery Photos"
    folder: "content/photos"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string", required: false }